name: CI - Master

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
            #   - name: Run Tests
            #     run: |
            - name: Set up SSH
              run: |
                  mkdir -p ~/.ssh/
                  echo "$SSH_PRIVATE_KEY" > ./deploy.key
                  chmod 600 ./deploy.key
                  echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                  SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
            - name: Install PM2
              run: |
                  npm i pm2

            - name: Deploy
              run: |
                  git stash
                  ./node_modules/pm2/bin/pm2 deploy ecosystem.config.js production
              env:
                  DEPLOY_TARGET: ${{secrets.DEPLOY_TARGET}}
